title: 'Tecnologia 1º Eso'
subtitle: 'Apuntes profesor J. Castro'
theme: jekyll-theme-midnight
light: true
description: 'Apuntes de Tecnología'
acronym: TIE
exclude: [ '_drafts/2021/', '_drafts/2020' ]
baseurl: 'alu-mfp-aet-2324-alu0100825145.github.io/' # '/introduccion'
#url: https://ull-mfp-aet-2223.github.io/ull-mfp-aet-2223.github.io
guia_docente: https://www.ull.es/apps/guias/guias/view_guide_course/2223/125771143
show_downloads: false
calendario_academico: 
horarios_examenes: 
calendario_examenes: 
horarios_tutorias: 
organization: 
  url: https://github.com/ULL-MFP-AET-2223
  name: ULL-MFP-AET-2223
  master: https://github.dev/ULL-MFP-AET/ull-mfp-aet.github.io/blob/main/
profesor: "https://www.ull.es/apps/guias/guias/view_teacher_niu/984/crguezl/"
profesor_github: alu0100825145
chat: https://chat.google.com
future: true
dsi:
  apuntes: https://ull-esit-dsi-1819.github.io/dsi-1819/
sytws:
  url: https://ull-mii-sytws-1920.github.io/
disqus: 
  url: https://procesadores-de-lenguajes.disqus.com/embed.js
  comments: true
classroom: 
  url: "https://classroom.github.com/classrooms/108617085-ull-mfp-aet-2223"
  name: ULL-MFP-AET-2223
collections:
  tareas:
    output: true
temas:
# - title: 'Introducción al Desarrollo Colaborativo de Proyectos en la Nube'
#    url: '/tema0-introduccion/'
#    hover: 'introduccion'
# - title: 'Desarrollo Colaborativo de Proyectos en la Nube con GitHub Education'
#  url: '/tema1-github-education'
#  hover: 'github-education'
# - title: 'Desarrollo Colaborativo de Proyectos en la Nube con Google'
#  url: /tema2-google-app-scripts
#  hover: 'google-app-scripts' 
plugins:
  - jemoji

